### ISSUE TITLE
Model?

### ISSUE THREAD

**Issue by realliyifei** [valvoda/neuralTransducer#2]
May I ask which code snippet corresponds to the modeling (https://github.com/valvoda/neuralTransducer/tree/main/model)? Or what exactly should we place inside?

It is not mentioned in README and the folder is left blank in repo.

**Comment by valvoda** [comment]
Hi! I've updated the README Sorry for the confusion :) The model folder was just a placeholder for where the model would be saved. I got rid of it since an appropriate directory will be created automatically when you run the experiments.

**Comment by realliyifei** [comment]
Yes i figured it out! Thanks for updating :)
